CON-193 Update sttp version to 2.2.9
Patagona/pricemonitor-clients pull request #21
Opened 2023-01-20 14:46 UTC by patagona-snayyer

PR intends to the following:
- Update sttp version from 2.0.0 to 2.2.9
- Adapt generated client code to sttp 2.2.9
- Test the previously failing case when server responds with error status code
- Add test execution to jenkins pipeline

2023-01-20 15:32 UTC, patagona-anas requested changes

2023-01-20 15:32 UTC, patagona-anas commented on generate-clients.sh
> +      sed -i 's/case Left(ex).*/case Left(ex) => ex match \n \t\t\t\t\t\t\t\t\t { \n \t\t\t\t\t\t\t\t\t\t case e:HttpError => ME.error[T](new HttpException(response.code, response.statusText, e.body)
I am not able to follow what this piece of code is doing & how the given issue is resolved by this piece of code.

2023-01-20 15:32 UTC, patagona-anas commented on JenkinsGenerateClients
> +    stage('Test'){
Is it possible that we run Jenkins job to ensure that it's running as expected?

2023-01-20 15:41 UTC, mzahn86 requested changes

2023-01-20 15:41 UTC, mzahn86 commented on clients/pricemonitor-internal-scala-sttp/src/main/scala/com/patagona/pricemonitor/client/core/ApiInvoker.scala
> + 										 case e:DeserializationError[_] => ME.error[T](new HttpException(response.code, response.statusText, e.body))
are these all exceptions which can occur?

2023-01-20 16:15 UTC, patagona-snayyer commented on clients/pricemonitor-internal-scala-sttp/src/main/scala/com/patagona/pricemonitor/client/core/ApiInvoker.scala
> + 										 case e:DeserializationError[_] => ME.error[T](new HttpException(response.code, response.statusText, e.body))
Yes. Since it's a sealed abstract class. This is an exhaustive list of cases that can occur.

2023-01-20 16:22 UTC, patagona-snayyer commented on clients/pricemonitor-internal-scala-sttp/src/main/scala/com/patagona/pricemonitor/client/core/ApiInvoker.scala
> + 										 case e:DeserializationError[_] => ME.error[T](new HttpException(response.code, response.statusText, e.body))
Code from version 2.2.9:
`sealed abstract class ResponseError[+T](error: String) extends Exception(error)
case class HttpError(body: String, statusCode: StatusCode)
    extends ResponseError[Nothing](s"statusCode: $statusCode, response: $body")
case class DeserializationError[T: ShowError](body: String, error: T)
    extends ResponseError[T](implicitly[ShowError[T]].show(error))`

2023-01-25 10:00 UTC, patagona-snayyer commented on JenkinsGenerateClients
> +    stage('Test'){
I created a test job that only tests the implementation and does not publish clients, the logs show that the test in clients-test/pricemonitor-internal-scala-sttp-test was executed and it passed. You can take a look at the bottom of the logs to find the test. [1]
[[1]](https://build.service.patagona.de/job/generate-pricemonitor-clients-test/9/execution/node/39/log/)

2023-01-25 11:26 UTC, mzahn86 requested changes

2023-01-25 11:26 UTC, mzahn86 commented on JenkinsGenerateClients
> +    JVM_FLAGS="-J-XX:+CMSClassUnloadingEnabled -J-XX:MaxPermSize=256m -J-Xmx3g -J-Xss16M"
why do we need 3GB of heap space?
I guess 1GB is enough

2023-01-25 13:06 UTC, patagona-snayyer commented on JenkinsGenerateClients
> +    JVM_FLAGS="-J-XX:+CMSClassUnloadingEnabled -J-XX:MaxPermSize=256m -J-Xmx3g -J-Xss16M"
okay

2023-01-25 13:56 UTC, mzahn86 approved these changes

2023-01-25 14:15 UTC, merged